//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using ValidDemo.MyAnnotation;
    public partial class Emp
    {

        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [RegularExpression(@"\d{10}",ErrorMessage="Enter 10 Digit Number")]
        [Display(Name = "Contact No")]
        public string Contact_No { get; set; }

     
        [Display(Name = "Present Address")]
        [StringLength(50,MinimumLength=4,ErrorMessage="String Length Must be Between 4 to 40 Characters")]
        public string Address { get; set; }

      
        [Display(Name = "Postal Code")]
        [StringLength(5,MinimumLength=5,ErrorMessage="Enter 5 Digit Postal Code")]
        public string P_code { get; set; }

       
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [Display(Name="Quantity")]
        [Range(5,10)]
        public Nullable<int> qty { get; set; }

        [Display(Name="Date of Join")]

        [DateCheck("01/01/1900",ErrorMessage="Date Should Not be Greater than today's Date")]
        public Nullable<System.DateTime> doj { get; set; }
    }
}
